/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Payment;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-18T20:34:07.576Z")

@Validated
@Api(value = "v1", description = "the v1 API")
@RequestMapping(value = "/v2")
public interface V1Api {

    @ApiOperation(value = "", nickname = "getPaymentById", notes = "", response = Payment.class, tags={ "store", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Payment.class),
        @ApiResponse(code = 400, message = "Invalid PaymentId"),
        @ApiResponse(code = 404, message = "PaymentId not found") })
    @RequestMapping(value = "/v1/payments/{payment_order_id}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Payment> getPaymentById(@ApiParam(value = "",required=true) @PathVariable("payment_order_id") String paymentOrderId);


    @ApiOperation(value = "", nickname = "placePayment", notes = "", response = Payment.class, tags={ "store", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = Payment.class),
        @ApiResponse(code = 400, message = "Invalid Payment") })
    @RequestMapping(value = "/v1/payments",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Payment> placePayment(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Payment body);

}
